#!/bin/bash
# -T sets TTL, -b is payload size in kbytes, -t is duration in seconds
# usage: ./mcsend [multicast IP address]

TTL=10            # number of hops
payload=200k      # bytes per second generated
MTU=1370          # MTU size in bytes
duration=100000   # duration in seconds of traffic 

iperf -u -c $1 \
    -b ${payload} \
    -t ${duration} \
    -T ${TTL} \
    -l ${MTU}
